alias state 'git status'
alias log 'git log'
alias push 'git push'
alias pull 'git pull'
alias commit 'git commit -m'
alias commit-all 'git commit -am'
alias flow 'git flow'
alias add 'git add'
alias add-all 'git add -A :/'
